// Generated by scripts/build.mjs from src/host.js — do not edit directly.
// dsh-chatgpt-subscription — host half（静态 bundle 形态）
// 业务：ChatGPT 订阅官方 OAuth 绑定 + 令牌看护 + openai-codex 路由注册
// 独立插件：绑定/令牌管理；dsh-bottom-info-bar 只读令牌显示额度
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { createHash, randomBytes } from 'node:crypto'
import { createServer } from 'node:http'

const DATA_DIR = process.env.DSH_CHATGPT_DATA_DIR || join(homedir(), '.dsh', 'dsh-chatgpt-subscription')
const CODEX_BIND_FILE = process.env.DSH_CHATGPT_BIND_FILE || join(DATA_DIR, 'codex-bind.json')

const CODEX_OAUTH_CLIENT_ID = 'app_EMoamEEZ73f0CkXaXp7hrann' // OpenAI OAuth 公开 client_id（token 续期用，非密钥）
const CODEX_DEFAULT_MODEL = process.env.DSH_CHATGPT_DEFAULT_MODEL || 'gpt-5.6-luna'
const ROUTING_SYNC_INTERVAL_MS = 3000
const SEARCH_SETTINGS_NAMESPACE = 'web-search-deepseek'
const DEEPSEEK_SEARCH_KEY_REF = 'DEEPSEEK_API_KEY'
const CHATGPT_SEARCH_DISABLED_KEY_REF = 'DSH_CHATGPT_SEARCH_DISABLED'
const CODEX_AUTH_FILE = process.env.DSH_CHATGPT_AUTH || join(homedir(), '.codex', 'auth.json')
const OAUTH_CALLBACK_TIMEOUT_MS = Number(process.env.DSH_CHATGPT_OAUTH_TIMEOUT_MS) > 0 ? Number(process.env.DSH_CHATGPT_OAUTH_TIMEOUT_MS) : 5 * 60 * 1000
const OAUTH_CALLBACK_PATH = '/auth/callback'

// 纯路由判定便于回归测试：只有已绑定且令牌状态健康、当前默认选择为 ChatGPT，
// 才能进入 ChatGPT 模式；其他情况都回到 DeepSeek 模式。
function routingModeFor(bound, bridgeHealthy, provider) {
  return bound === true && bridgeHealthy === true && provider === 'openai-codex' ? 'chatgpt' : 'deepseek'
}

const CODEX_JWT_ACCOUNT_CLAIM = 'https://api.openai.com/auth' // access_token JWT payload 里账号声明的命名空间键（wham 账号提取用）
const OAUTH_SCOPE = 'openid profile email offline_access' // 官方授权 scope（与 pi-ai/Codex CLI 一致；offline_access 换 refresh_token）

// ---------- 绑定标记（严格官方模式唯一事实） ----------
// 语义：只有本插件 OAuth 绑定成功写入的标记存在且 bound=true 时，才注入令牌到 DSH 凭据。
// codex CLI 自己的令牌（无标记）绝不被自动使用——彻底废弃旧"读登录态"桥接来源。
// 文件路径可由 DSH_CHATGPT_BIND_FILE 覆盖（测试隔离）。
function readBindFlag(filePath) {
  if (typeof filePath !== 'string' || filePath.length === 0) filePath = CODEX_BIND_FILE
  let raw = null
  try {
    raw = readFileSync(filePath, 'utf8')
  } catch (err) {
    return { ok: false, bound: false }
  }
  try {
    const data = JSON.parse(raw)
    if (!data || typeof data !== 'object' || Array.isArray(data)) return { ok: false, bound: false }
    return {
      ok: true,
      bound: data.bound === true,
      routeOwned: data.routeOwned === true,
      defaultModelManaged: data.defaultModelManaged === true,
      previousDefaultModel: data.previousDefaultModel && typeof data.previousDefaultModel === 'object' ? data.previousDefaultModel : null,
      searchModeManaged: data.searchModeManaged === true,
      credentialManaged: data.credentialManaged === true,
      previousSearchKeyRef: typeof data.previousSearchKeyRef === 'string' && data.previousSearchKeyRef.length > 0 ? data.previousSearchKeyRef : null,
    }
  } catch (err) {
    return { ok: false, bound: false }
  }
}

// 原子写绑定标记（tmp+rename 防写一半；0600；目录自动创建）；data 可带 plan 等扩展字段
function writeBindFlag(filePath, data) {
  const payload = Object.assign({ bound: true, boundAt: new Date().toISOString() }, data || {})
  const tmp = filePath + '.tmp'
  mkdirSync(dirname(filePath), { recursive: true, mode: 0o700 })
  writeFileSync(tmp, JSON.stringify(payload, null, 2) + '\n', { mode: 0o600 })
  chmodSync(tmp, 0o600)
  renameSync(tmp, filePath)
  chmodSync(filePath, 0o600)
  return payload
}

// 清绑定标记（删除文件）；文件已缺失视为已清，不抛错
function clearBindFlag(filePath) {
  if (typeof filePath !== 'string' || filePath.length === 0) filePath = CODEX_BIND_FILE
  try {
    unlinkSync(filePath)
  } catch (err) {
    if (!err || err.code !== 'ENOENT') throw err
  }
}

const CODEX_TOKEN_FALLBACK_LIFETIME_SEC = 864000
// 过期前提前量（秒）：JWT 剩余寿命 < 45 分钟才续期（10 天寿命下极少触发，避免窗口内过期）
const CODEX_REFRESH_AHEAD_SEC = 45 * 60
// 桥接同步周期（毫秒）：启动即跑一次 + 每 30 分钟维护（与订阅额度刷新相互独立）
const CODEX_SYNC_INTERVAL_MS = 30 * 60 * 1000

// base64url → UTF-8 字符串（JWT payload 段解码：-/_ 换回 +// 后按标准 base64 解，容忍缺 padding）
function decodeBase64Url(input) {
  if (typeof input !== 'string' || input.length === 0) return null
  try {
    return Buffer.from(input.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8')
  } catch (err) {
    return null
  }
}

// JWT exp 解码（秒）：标准 JWT 取第 2 段 payload 的 exp；非 JWT/损坏/缺 exp → null（调用方走 last_refresh 兜底）
function decodeJwtExp(token) {
  if (typeof token !== 'string' || token.length === 0) return null
  const parts = token.split('.')
  if (parts.length !== 3) return null
  const raw = decodeBase64Url(parts[1])
  if (raw == null) return null
  let payload = null
  try { payload = JSON.parse(raw) } catch (err) { return null }
  const exp = payload && payload.exp
  return typeof exp === 'number' && isFinite(exp) && exp > 0 ? exp : null
}

// 归一化令牌过期时刻（秒）：JWT exp 优先；无效 → last_refresh（毫秒）+ 10 天兜底；两者皆无 → null
function codexExpiresAt(expSeconds, lastRefreshMs) {
  if (typeof expSeconds === 'number' && isFinite(expSeconds) && expSeconds > 0) return expSeconds
  if (typeof lastRefreshMs === 'number' && isFinite(lastRefreshMs) && lastRefreshMs > 0) {
    return Math.floor(lastRefreshMs / 1000) + CODEX_TOKEN_FALLBACK_LIFETIME_SEC
  }
  return null
}

// 续期决策（秒精度）：剩余 < 45 分钟或无法判定过期 → true（保守续期，宁多刷不放过期）
function codexNeedsRefresh(expiresAtSeconds, nowSeconds) {
  if (expiresAtSeconds == null) return true
  return expiresAtSeconds - nowSeconds < CODEX_REFRESH_AHEAD_SEC
}

// 读 auth.json：{ ok:true, auth } 或 { ok:false, reason:'missing'|'corrupt' }（缺失/损坏一律不抛异常）
function readCodexAuthFile(filePath) {
  let raw = null
  try {
    raw = readFileSync(filePath, 'utf8')
  } catch (err) {
    return { ok: false, reason: err && err.code === 'ENOENT' ? 'missing' : 'corrupt' }
  }
  let auth = null
  try {
    auth = JSON.parse(raw)
  } catch (err) {
    return { ok: false, reason: 'corrupt' }
  }
  if (!auth || typeof auth !== 'object' || Array.isArray(auth)) return { ok: false, reason: 'corrupt' }
  return { ok: true, auth: auth }
}

// 原子写回 auth.json：只更新 access_token/refresh_token/last_refresh，保留完整结构（auth_mode/OPENAI_API_KEY/
// tokens 内 account_id、id_token 等一律不动——绝不弄坏 Codex CLI 登录态）；tmp+rename 防写一半；0600 权限
function writeAuthJson(filePath, currentAuth, accessToken, refreshToken, lastRefreshIso) {
  const updated = {
    ...currentAuth,
    tokens: { ...(currentAuth.tokens && typeof currentAuth.tokens === 'object' ? currentAuth.tokens : {}), access_token: accessToken, refresh_token: refreshToken },
    last_refresh: lastRefreshIso,
  }
  const tmp = filePath + '.tmp'
  writeFileSync(tmp, JSON.stringify(updated, null, 2) + '\n', { mode: 0o600 })
  chmodSync(tmp, 0o600)
  renameSync(tmp, filePath)
  chmodSync(filePath, 0o600)
  return updated
}

// 用 refresh_token 向官方 OAuth 端点换新令牌对；凭据仅经 HTTPS body 传递（不进子进程，无 shell 注入面）
// 响应缺 access_token（空串/null）→ 返回 null（调用方不得写回）；refresh_token 未轮换 → 返回 null 字段表示沿用旧值
async function refreshCodexTokenPair(refreshToken) {
  try {
    const res = await fetch('https://auth.openai.com/oauth/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'refresh_token',
        client_id: CODEX_OAUTH_CLIENT_ID,
        refresh_token: refreshToken,
      }).toString(),
      signal: AbortSignal.timeout(15000),
    })
    if (!res.ok) return null
    const body = await res.json()
    if (!body || typeof body.access_token !== 'string' || body.access_token.length === 0) return null
    return {
      access_token: body.access_token,
      refresh_token: typeof body.refresh_token === 'string' && body.refresh_token.length > 0 ? body.refresh_token : null,
    }
  } catch (err) {
    return null // 网络/超时等异常 → 调用方按"续期失败"降级（保留旧凭据）
  }
}

// ---------- ChatGPT 订阅官方 OAuth 绑定（v1.2.0）纯逻辑：PKCE / 授权 URL / 回调解析 / 令牌交换 / 写回 ----------
// 安全铁律：verifier/state/令牌仅内存（verifier 用完即弃）；不打印、不进日志、不进仓库；唯一落盘 =
// ~/.codex/auth.json（0600）与 DSH 凭据库（0600）；回调 server 仅 127.0.0.1 + state 校验防 CSRF。

// OAuth 回调端口：生产必须为 1455（redirect_uri 与 OpenAI 注册值固定一致）；DSH_CHATGPT_OAUTH_PORT 仅测试隔离用
function oauthCallbackPort() {
  const v = Number(process.env.DSH_CHATGPT_OAUTH_PORT)
  return Number.isInteger(v) && v > 0 && v < 65536 ? v : 1455
}

// PKCE 对：verifier = 32 字节 base64url；challenge = 对 verifier 做 sha256 哈希后再 base64url 编码（S256）
function createPkcePair() {
  const verifier = randomBytes(32).toString('base64url')
  const challenge = createHash('sha256').update(verifier).digest('base64url')
  return { verifier: verifier, challenge: challenge }
}

// 构造授权跳转 URL（auth.openai.com/oauth/authorize；参数与 pi-ai/Codex CLI 一致；不含任何机密）
function buildAuthorizeUrl(state, codeChallenge) {
  const url = new URL('https://auth.openai.com/oauth/authorize')
  url.searchParams.set('client_id', CODEX_OAUTH_CLIENT_ID)
  url.searchParams.set('response_type', 'code')
  url.searchParams.set('redirect_uri', 'http://localhost:' + oauthCallbackPort() + OAUTH_CALLBACK_PATH)
  url.searchParams.set('code_challenge', codeChallenge)
  url.searchParams.set('code_challenge_method', 'S256')
  url.searchParams.set('state', state)
  url.searchParams.set('scope', OAUTH_SCOPE)
  return url.toString()
}

// 解析回调（完整 URL 的 query/hash、查询串、手贴 'code#state'、裸 code）；缺参返回 null 字段
function parseCallbackUrl(url) {
  if (typeof url !== 'string' || url.length === 0) return { code: null, state: null }
  const raw = url.trim()
  // ① 完整 URL：query 参数优先，hash 参数兜底（兼容 OAuth hash 响应）
  try {
    const u = new URL(raw)
    let code = u.searchParams.get('code')
    let state = u.searchParams.get('state')
    if (u.hash && u.hash.length > 1) {
      const hp = new URLSearchParams(u.hash.slice(1))
      if (code == null) code = hp.get('code')
      if (state == null) state = hp.get('state')
    }
    return { code: code, state: state }
  } catch (err) { /* 非完整 URL → ②/③/④ */ }
  // ② 手贴格式 'code#state'
  if (raw.indexOf('#') >= 0 && raw.indexOf('://') < 0) {
    const parts = raw.split('#')
    const first = parts[0]
    if (first && first.indexOf('=') < 0) {
      const rest = parts.slice(1).join('#')
      const sp = new URLSearchParams(rest)
      return { code: first, state: sp.get('state') != null ? sp.get('state') : rest }
    }
  }
  // ③ 查询串 'code=..&state=..'
  const q = raw.indexOf('?') >= 0 ? raw.slice(raw.indexOf('?') + 1) : raw
  const sp2 = new URLSearchParams(q)
  if (sp2.has('code') || sp2.has('state')) return { code: sp2.get('code'), state: sp2.get('state') }
  // ④ 裸 code（手动粘贴单值）
  if (raw.length > 0 && raw.indexOf('=') < 0 && raw.indexOf('#') < 0) return { code: raw, state: null }
  return { code: null, state: null }
}

// 从 access_token JWT payload 提取 chatgpt_account_id（wham 额度接口所需）；失败 → null
function codexAccountIdFromJwt(token) {
  if (typeof token !== 'string' || token.length === 0) return null
  const parts = token.split('.')
  if (parts.length !== 3) return null
  const raw = decodeBase64Url(parts[1])
  if (raw == null) return null
  let payload = null
  try { payload = JSON.parse(raw) } catch (err) { return null }
  const auth = payload && payload[CODEX_JWT_ACCOUNT_CLAIM]
  const id = auth && auth.chatgpt_account_id
  return typeof id === 'string' && id.length > 0 ? id : null
}

// 构造 OAuth 绑定后的 auth.json 对象：保留既有结构（codex CLI/OpenCode 兼容），仅替换令牌字段 + last_refresh；
// account_id 优先从新 access_token 提取，提取失败保留旧值；全新文件给出标准骨架 {auth_mode:'oauth', ...}
function buildOAuthAuthObject(existing, exchange, nowIso) {
  const base = existing && typeof existing === 'object' && !Array.isArray(existing) ? existing : {}
  const baseTokens = base.tokens && typeof base.tokens === 'object' && !Array.isArray(base.tokens) ? base.tokens : {}
  const tokens = Object.assign({}, baseTokens)
  tokens.access_token = exchange.access_token
  if (typeof exchange.refresh_token === 'string' && exchange.refresh_token.length > 0) tokens.refresh_token = exchange.refresh_token
  if (typeof exchange.id_token === 'string' && exchange.id_token.length > 0) tokens.id_token = exchange.id_token
  const accountId = codexAccountIdFromJwt(exchange.access_token)
  if (accountId) tokens.account_id = accountId
  return {
    auth_mode: 'oauth',
    OPENAI_API_KEY: typeof base.OPENAI_API_KEY === 'string' && base.OPENAI_API_KEY.length > 0 ? base.OPENAI_API_KEY : null,
    tokens: tokens,
    last_refresh: nowIso,
  }
}

// 解绑：仅清令牌字段并原子写回（保留 auth_mode/OPENAI_API_KEY/account_id 等结构——auth.json 是 codex CLI
// 等工具共用的标准位置，保留骨架更接近"已登出"语义，也便于重新绑定与 CLI 兼容）；tmp+rename 防写一半；0600
function clearCodexAuthTokens(filePath, currentAuth) {
  const base = currentAuth && typeof currentAuth === 'object' && !Array.isArray(currentAuth) ? currentAuth : {}
  const tokens = Object.assign({}, base.tokens && typeof base.tokens === 'object' && !Array.isArray(base.tokens) ? base.tokens : {})
  delete tokens.access_token
  delete tokens.refresh_token
  delete tokens.id_token
  const updated = Object.assign({}, base, { tokens: tokens, last_refresh: null })
  const tmp = filePath + '.tmp'
  writeFileSync(tmp, JSON.stringify(updated, null, 2) + '\n', { mode: 0o600 })
  chmodSync(tmp, 0o600)
  renameSync(tmp, filePath)
  chmodSync(filePath, 0o600)
  return updated
}

// 用授权码向官方端点换令牌对（PKCE verifier 证明持码者身份）；凭据仅经 HTTPS body 传递（不进子进程）；
// 响应缺 access_token → { ok:false }（调用方不得写回）；网络/超时异常 → { ok:false, status:null }
async function exchangeAuthorizationCode(code, verifier) {
  try {
    const res = await fetch('https://auth.openai.com/oauth/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: CODEX_OAUTH_CLIENT_ID,
        code: code,
        code_verifier: verifier,
        redirect_uri: 'http://localhost:' + oauthCallbackPort() + OAUTH_CALLBACK_PATH,
      }).toString(),
      signal: AbortSignal.timeout(15000),
    })
    if (!res.ok) return { ok: false, status: res.status }
    const body = await res.json()
    if (!body || typeof body.access_token !== 'string' || body.access_token.length === 0) return { ok: false, status: res.status }
    return {
      ok: true,
      access_token: body.access_token,
      refresh_token: typeof body.refresh_token === 'string' && body.refresh_token.length > 0 ? body.refresh_token : null,
      id_token: typeof body.id_token === 'string' && body.id_token.length > 0 ? body.id_token : null,
    }
  } catch (err) {
    return { ok: false, status: null } // 网络/超时等异常 → 调用方按"交换失败"处理
  }
}

// 本地回调 server：仅监听 127.0.0.1；仅接受 /auth/callback；校验 state（防 CSRF/中间人）；
// 端口占用（EADDRINUSE）等监听失败 → resolve(null)（调用方返回明确错误，不崩溃）
function startOAuthCallbackServer(expectedState, onCode, port) {
  return new Promise(function (resolve) {
    let settled = false
    const fail = function () { if (!settled) { settled = true; resolve(null) } }
    const server = createServer(function (req, res) {
      let pathname = '/'
      let params = null
      try {
        const url = new URL(req.url || '/', 'http://localhost')
        pathname = url.pathname
        params = url.searchParams
      } catch (err) {
        respondOAuthPage(res, 400, 'OAuth 回调地址无效')
        return
      }
      if (pathname !== OAUTH_CALLBACK_PATH) {
        respondOAuthPage(res, 404, '回调路径不存在')
        return
      }
      if (params.get('state') !== expectedState) {
        respondOAuthPage(res, 400, 'OAuth 状态校验失败，请重试')
        return
      }
      const code = params.get('code')
      if (!code) {
        respondOAuthPage(res, 400, '缺少授权码')
        return
      }
      respondOAuthPage(res, 200, '授权完成，可关闭此页')
      onCode(code)
    })
    server.on('error', fail)
    server.listen(port, '127.0.0.1', function () {
      if (!settled) {
        settled = true
        resolve({
          server: server,
          port: port,
          close: function () { try { server.close() } catch (err) { /* 忽略 */ } },
        })
      }
    })
  })
}

// 回调页响应（纯静态 HTML，无用户输入拼接风险；message 均为本模块常量）
function respondOAuthPage(res, status, message) {
  const safe = String(message).replace(/[&<>"']/g, function (c) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  })
  const html = '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><title>ChatGPT 授权</title></head>' +
    '<body style="font-family:system-ui,sans-serif;padding:3rem 2rem;text-align:center;background:#f7f7f8">' +
    '<h2 style="color:#0d0d0d">' + safe + '</h2>' +
    '<p style="color:#555">你可以关闭此页面，返回 DSH 继续。</p>' +
    '</body></html>'
  res.statusCode = status
  res.setHeader('Content-Type', 'text/html; charset=utf-8')
  res.setHeader('Cache-Control', 'no-store')
  res.end(html)
}

// ============================================================================
// apply：ChatGPT 订阅官方 OAuth 绑定 + 令牌看护 + openai-codex 路由注册
// ============================================================================
export default {
  inject: ['credentials', 'settings', 'timer', 'shell'],
  apply(ctx) {
    mkdirSync(DATA_DIR, { recursive: true, mode: 0o700 })
    chmodSync(DATA_DIR, 0o700)
    // ---------- 状态 ----------
    let codexBridgeState = { ok: false, lastSyncAt: null, expiresAt: null, error: null, routeConfigured: false };
    let codexInjectedToken = null; // 最近成功注入 DSH 凭据的令牌（仅内存比对，防同值重复写盘）
    let oauthInFlight = false; // OAuth 授权进行中（防并发：绝不同时存在两个回调 server/state）
    let oauthLastError = null; // 最近一次 OAuth 流程错误（状态 RPC 透出；令牌值永不进入）
    let syncInFlight = null; // 周期同步与 OAuth 后同步共享单飞锁，避免交叉读写凭据
    let routingInFlight = null; // 模型选择与搜索线路切换共享单飞锁
    let codexRouteOwned = false; // 进程内保留所有权，绑定标记缺失时仍可安全清理插件路由
    let codexCredentialOwned = false; // 只清理插件自己注入的凭据，绝不碰用户已有同名凭据
    let searchKeyRef = DEEPSEEK_SEARCH_KEY_REF;
    let searchMode = null;

    // ---------- 路由注册（仅绑定时启用；用户同名路由绝不覆盖） ----------
    async function ensureCodexRoute(flag) {
      const settings = ctx.settings || ctx.get('settings');
      if (!settings || typeof settings.get !== 'function' || typeof settings.mutate !== 'function') {
        return { ok: false, owned: false, message: 'settings 服务未就绪，下个周期重试' };
      }
      try {
        const cur = settings.get('llm-pi-ai');
        const providers = cur && typeof cur === 'object' && cur.providers && typeof cur.providers === 'object' ? cur.providers : {};
        const existing = providers['openai-codex'];
        if (existing && existing.apiKeyEnv !== 'OPENAI_CODEX_API_KEY') {
          return { ok: false, owned: false, message: '检测到用户自定义的 openai-codex 路由（apiKeyEnv 不是 OPENAI_CODEX_API_KEY），插件不会覆盖' };
        }
        if (existing) {
          // 只有绑定标记证明是插件旧版本创建的路由时才升级；同名用户路由只读不删不改。
          if (flag && flag.routeOwned === true) {
            const patch = {};
            if (existing.displayName === 'Codex') patch.displayName = 'ChatGPT';
            if (existing.transport !== 'sse') patch.transport = 'sse';
            if (Object.keys(patch).length > 0) await settings.mutate('llm-pi-ai', [{ op: 'set', path: ['providers', 'openai-codex'], value: Object.assign({}, existing, patch) }]);
          }
          return { ok: true, owned: Boolean(flag && flag.routeOwned === true) };
        }
        await settings.mutate('llm-pi-ai', [{ op: 'set', path: ['providers', 'openai-codex'], value: { apiKeyEnv: 'OPENAI_CODEX_API_KEY', displayName: 'ChatGPT', transport: 'sse' } }]);
        return { ok: true, owned: true };
      } catch (err) {
        return { ok: false, owned: false, message: 'openai-codex 路由注册失败，稍后重试' };
      }
    }

    async function removeOwnedCodexRoute(flag) {
      if (!flag.routeOwned && !codexRouteOwned) return;
      const settings = ctx.settings || ctx.get('settings');
      if (!settings || typeof settings.get !== 'function' || typeof settings.mutate !== 'function') return;
      const cur = settings.get('llm-pi-ai');
      const route = cur && cur.providers && cur.providers['openai-codex'];
      if (route && route.apiKeyEnv === 'OPENAI_CODEX_API_KEY') {
        await settings.mutate('llm-pi-ai', [{ op: 'unset', path: ['providers', 'openai-codex'] }]);
      }
    }

    async function configureDefaultModel() {
      const service = ctx.get('agentDefaultModel');
      if (!service || typeof service.currentSelection !== 'function' || typeof service.saveSelection !== 'function') return { ok: false, previous: null, message: '默认模型服务未就绪，无法安全切换到 ChatGPT' };
      const current = service.currentSelection();
      if (!current || current.provider === 'openai-codex') return { ok: true, previous: null };
      await service.saveSelection({ provider: 'openai-codex', model: CODEX_DEFAULT_MODEL, reasoningEffort: current.reasoningEffort });
      return { ok: true, previous: current };
    }

    async function restoreDefaultModel(flag) {
      if (!flag.defaultModelManaged || !flag.previousDefaultModel) return;
      const service = ctx.get('agentDefaultModel');
      if (!service || typeof service.currentSelection !== 'function' || typeof service.saveSelection !== 'function') return;
      const current = service.currentSelection();
      if (current && current.provider === 'openai-codex') await service.saveSelection(flag.previousDefaultModel);
    }

    // 搜索 provider 的配置按每次调用投影；用不存在的凭据引用实现 ChatGPT 模式 fail closed，
    // 再切回 DeepSeek 时恢复原引用，不删除用户的 DeepSeek 密钥。
    async function setSearchMode(mode) {
      if (mode !== 'chatgpt' && mode !== 'deepseek') return { ok: false, message: '未知线路模式' };
      if (searchMode === mode) return { ok: true, mode: mode };
      const settings = ctx.settings || ctx.get('settings');
      if (!settings || typeof settings.get !== 'function' || typeof settings.mutate !== 'function') {
        return { ok: false, message: '搜索设置服务未就绪，无法安全切换搜索线路' };
      }
      try {
        const current = settings.get(SEARCH_SETTINGS_NAMESPACE);
        if (current && typeof current.apiKeyEnv === 'string' && current.apiKeyEnv !== CHATGPT_SEARCH_DISABLED_KEY_REF) {
          searchKeyRef = current.apiKeyEnv;
        }
        const nextRef = mode === 'chatgpt' ? CHATGPT_SEARCH_DISABLED_KEY_REF : searchKeyRef;
        if (!current || current.apiKeyEnv !== nextRef) {
          await settings.mutate(SEARCH_SETTINGS_NAMESPACE, [{ op: 'set', path: ['apiKeyEnv'], value: nextRef }]);
        }
        searchMode = mode;
        return { ok: true, mode: mode };
      } catch (err) {
        return { ok: false, message: '搜索线路切换失败，已保持原线路' };
      }
    }

    async function syncRoutingMode() {
      if (routingInFlight) return routingInFlight;
      routingInFlight = (async function () {
        const flag = readBindFlag(CODEX_BIND_FILE);
        if (searchMode === null && flag.previousSearchKeyRef) searchKeyRef = flag.previousSearchKeyRef;
        const service = ctx.get('agentDefaultModel');
        const selection = service && typeof service.currentSelection === 'function' ? service.currentSelection() : null;
        const mode = routingModeFor(flag.bound, codexBridgeState.ok, selection && selection.provider);
        return setSearchMode(mode);
      })().finally(function () { routingInFlight = null; });
      return routingInFlight;
    }

    // ---------- 令牌看护（严格官方模式：绑定标记唯一事实） ----------
    async function clearInjectedCodexCredential(flag) {
      if (!codexCredentialOwned && !(flag && flag.credentialManaged === true)) return true;
      try {
        await ctx.credentials.unset('OPENAI_CODEX_API_KEY');
        codexInjectedToken = null;
        codexCredentialOwned = false;
        return true;
      } catch (err) {
        codexInjectedToken = null;
        return false;
      }
    }

    async function syncCodexToken() {
      if (syncInFlight) return syncInFlight;
      syncInFlight = syncCodexTokenOnce().catch(function () {
        codexBridgeState = { ok: false, lastSyncAt: Date.now(), expiresAt: null, error: { kind: 'exception', message: '同步异常' }, routeConfigured: codexBridgeState.routeConfigured };
      }).finally(function () { syncInFlight = null; });
      return syncInFlight;
    }

    async function syncCodexTokenOnce() {
      const nowMs = Date.now();
      const nowSec = Math.floor(nowMs / 1000);
      const flag = readBindFlag(CODEX_BIND_FILE);
      if (!flag.bound) {
        const cleared = await clearInjectedCodexCredential(flag);
        try { await removeOwnedCodexRoute(flag); codexRouteOwned = false; } catch (err) {
          codexBridgeState = { ok: false, lastSyncAt: nowMs, expiresAt: null, error: { kind: 'route-cleanup', message: '解绑路由清理失败' }, routeConfigured: true };
          return;
        }
        codexBridgeState = { ok: false, lastSyncAt: nowMs, expiresAt: null, error: cleared ? { kind: 'unbound', message: '未绑定 ChatGPT 订阅，请在 DSH 设置「订阅」页授权绑定' } : { kind: 'credentials-cleanup', message: '未绑定，但旧凭据清理失败' }, routeConfigured: false };
        return;
      }
      if (!codexBridgeState.routeConfigured) {
        const route = await ensureCodexRoute(flag);
        if (!route.ok) {
          codexBridgeState = { ok: false, lastSyncAt: nowMs, expiresAt: null, error: { kind: 'route-conflict', message: route.message }, routeConfigured: false };
          return;
        }
        codexRouteOwned = route.owned;
        codexBridgeState.routeConfigured = true;
      }
      const read = readCodexAuthFile(CODEX_AUTH_FILE);
      if (!read.ok) {
        const cleared = await clearInjectedCodexCredential(flag);
        let routeRemoved = true;
        try { await removeOwnedCodexRoute(flag); codexRouteOwned = false; } catch (err) { routeRemoved = false; }
        const error = !routeRemoved ? { kind: 'route-cleanup', message: '绑定失效且路由清理失败' } : cleared ? { kind: 'no-login', message: '绑定已失效：未找到登录凭证，请重新授权' } : { kind: 'credentials-cleanup', message: '登录凭证缺失且旧凭据清理失败' };
        codexBridgeState = { ok: false, lastSyncAt: nowMs, expiresAt: null, error: error, routeConfigured: !routeRemoved };
        return;
      }
      const auth = read.auth;
      const tokens = auth.tokens && typeof auth.tokens === 'object' ? auth.tokens : {};
      const access = typeof tokens.access_token === 'string' ? tokens.access_token : '';
      const refresh = typeof tokens.refresh_token === 'string' ? tokens.refresh_token : '';
      const lastRefreshMs = Date.parse(auth.last_refresh);
      if (!access) {
        const cleared = await clearInjectedCodexCredential(flag);
        let routeRemoved = true;
        try { await removeOwnedCodexRoute(flag); codexRouteOwned = false; } catch (err) { routeRemoved = false; }
        const error = !routeRemoved ? { kind: 'route-cleanup', message: '绑定失效且路由清理失败' } : cleared ? { kind: 'no-key', message: '绑定已失效：缺少 access_token，请重新授权' } : { kind: 'credentials-cleanup', message: '缺少 access_token 且旧凭据清理失败' };
        codexBridgeState = { ok: false, lastSyncAt: nowMs, expiresAt: null, error: error, routeConfigured: !routeRemoved };
        return;
      }
      let expiresAtSec = codexExpiresAt(decodeJwtExp(access), lastRefreshMs);
      let token = null;
      let error = null;

      if (codexNeedsRefresh(expiresAtSec, nowSec)) {
        if (!refresh) {
          error = { kind: 'auth', message: '令牌临近过期但缺少 refresh_token，请重新授权' };
        } else {
          const pair = await refreshCodexTokenPair(refresh);
          if (pair) {
            try {
              const nextRefresh = pair.refresh_token || refresh;
              const updated = writeAuthJson(CODEX_AUTH_FILE, auth, pair.access_token, nextRefresh, new Date().toISOString());
              token = pair.access_token;
              expiresAtSec = codexExpiresAt(decodeJwtExp(pair.access_token), Date.parse(updated.last_refresh));
            } catch (err) {
              token = pair.access_token;
              expiresAtSec = codexExpiresAt(decodeJwtExp(pair.access_token), nowMs);
              error = { kind: 'write', message: '续期成功但写回 auth.json 失败' };
            }
          } else {
            const reRead = readCodexAuthFile(CODEX_AUTH_FILE);
            const reAuth = reRead.ok ? reRead.auth : null;
            const reTokens = reAuth && reAuth.tokens && typeof reAuth.tokens === 'object' ? reAuth.tokens : {};
            const reAccess = typeof reTokens.access_token === 'string' ? reTokens.access_token : '';
            const reRefreshMs = reAuth && typeof reAuth.last_refresh === 'string' ? Date.parse(reAuth.last_refresh) : NaN;
            if (reAuth && reAccess && !isNaN(reRefreshMs) && (isNaN(lastRefreshMs) || reRefreshMs > lastRefreshMs)) {
              token = reAccess;
              expiresAtSec = codexExpiresAt(decodeJwtExp(reAccess), reRefreshMs);
            } else {
              error = { kind: 'auth', message: '令牌续期失败（refresh_token 可能失效），请重新授权' };
            }
          }
        }
      } else {
        token = access;
      }

      if (!token && error) {
        const cleared = await clearInjectedCodexCredential(flag);
        if (!cleared) error = { kind: 'credentials-cleanup', message: '令牌不可用且旧凭据清理失败' };
      }
      if (token && token !== codexInjectedToken) {
        try {
          await ctx.credentials.set('OPENAI_CODEX_API_KEY', token);
          codexInjectedToken = token;
          codexCredentialOwned = true;
        } catch (err) {
          const cleared = await clearInjectedCodexCredential(flag);
          error = cleared ? { kind: 'credentials', message: '凭据注入失败' } : { kind: 'credentials-cleanup', message: '凭据注入和旧凭据清理均失败' };
        }
      }
      codexBridgeState = { ok: !error, lastSyncAt: nowMs, expiresAt: expiresAtSec != null ? expiresAtSec * 1000 : null, error: error, routeConfigured: codexBridgeState.routeConfigured };
    }

    // ---------- OAuth 官方绑定（PKCE + state + 本地回调 127.0.0.1） ----------
    function deferred() {
      let resolve = null;
      const promise = new Promise(function (res) { resolve = res; });
      return { promise: promise, resolve: resolve };
    }

    async function openOAuthBrowser(authorizeUrl) {
      const shell = (ctx && ctx.shell) || ctx.get('shell');
      if (!shell || typeof shell.run !== 'function') return false;
      const platform = typeof process !== 'undefined' && process.platform ? process.platform : '';
      const openCmd = platform === 'darwin' ? 'open' : platform === 'win32' ? 'cmd /c start ""' : 'xdg-open';
      const safeUrl = String(authorizeUrl).replace(/["$`\\]/g, '\\$&');
      const request = { command: openCmd + ' "' + safeUrl + '"' };
      try {
        const result = await shell.run(typeof shell.resolve === 'function' ? shell.resolve(request) : request);
        return !result || result.exitCode === 0 || result.exitCode === undefined;
      } catch (err) {
        return false;
      }
    }

    async function rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken) {
      if (previousAuth !== undefined && typeof newAccessToken === 'string') {
        try {
          const current = readCodexAuthFile(CODEX_AUTH_FILE);
          const currentTokens = current.ok && current.auth.tokens && typeof current.auth.tokens === 'object' ? current.auth.tokens : {};
          if (current.ok && currentTokens.access_token === newAccessToken) {
            if (previousAuth === null) unlinkSync(CODEX_AUTH_FILE);
            else {
              const previousTokens = previousAuth.tokens && typeof previousAuth.tokens === 'object' ? previousAuth.tokens : {};
              writeAuthJson(CODEX_AUTH_FILE, previousAuth, typeof previousTokens.access_token === 'string' ? previousTokens.access_token : '', typeof previousTokens.refresh_token === 'string' ? previousTokens.refresh_token : null, previousAuth.last_refresh || null);
            }
          }
        } catch (err) {}
      }
      if (defaultModel && defaultModel.previous) {
        try { await restoreDefaultModel({ defaultModelManaged: true, previousDefaultModel: defaultModel.previous }); } catch (err) {}
      }
      if (route && route.ok) {
        try { await removeOwnedCodexRoute({ routeOwned: route.owned }); } catch (err) {}
      }
      codexRouteOwned = false;
    }

    async function runCodexOAuthFlow(pkce, state, serverHandle, authorizeUrl, waitCode) {
      let timer = null;
      let route = null;
      let defaultModel = null;
      let previousAuth = undefined;
      let newAccessToken = null;
      try {
        await openOAuthBrowser(authorizeUrl);
        const code = await Promise.race([
          waitCode.promise,
          new Promise(function (resolve) { timer = setTimeout(function () { resolve(null); }, OAUTH_CALLBACK_TIMEOUT_MS); }),
        ]);
        if (!code) { oauthLastError = { kind: 'timeout', message: '授权超时（5 分钟），请重试' }; return; }
        const exchanged = await exchangeAuthorizationCode(code, pkce.verifier);
        if (!exchanged.ok) {
          oauthLastError = { kind: 'exchange', message: '令牌交换失败（' + (exchanged.status != null ? 'HTTP ' + exchanged.status : '网络错误') + '），请重试' };
          return;
        }
        const nowIso = new Date().toISOString();
        const read = readCodexAuthFile(CODEX_AUTH_FILE);
        previousAuth = read.ok ? read.auth : null;
        newAccessToken = exchanged.access_token;
        const authToWrite = buildOAuthAuthObject(read.ok ? read.auth : null, exchanged, nowIso);
        try {
          writeAuthJson(CODEX_AUTH_FILE, authToWrite, exchanged.access_token, authToWrite.tokens.refresh_token != null ? authToWrite.tokens.refresh_token : null, nowIso);
        } catch (err) {
          oauthLastError = { kind: 'write', message: '绑定成功但写入 auth.json 失败' };
          return;
        }
        const priorFlag = readBindFlag(CODEX_BIND_FILE);
        route = await ensureCodexRoute(priorFlag);
        if (!route.ok) {
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'route-conflict', message: route.message };
          return;
        }
        codexRouteOwned = route.owned;
        try {
          defaultModel = await configureDefaultModel();
          if (!defaultModel.previous && priorFlag.defaultModelManaged) defaultModel.previous = priorFlag.previousDefaultModel;
        } catch (err) {
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'default-model', message: '绑定成功但默认模型切换失败，请检查设置后重试' };
          return;
        }
        if (!defaultModel.ok) {
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'default-model', message: defaultModel.message };
          return;
        }
        const searchRoute = await setSearchMode('chatgpt');
        if (!searchRoute.ok) {
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'search-route', message: searchRoute.message };
          return;
        }
        try {
          writeBindFlag(CODEX_BIND_FILE, {
            routeOwned: route.owned,
            defaultModelManaged: Boolean(defaultModel.previous),
            previousDefaultModel: defaultModel.previous,
            searchModeManaged: true,
            credentialManaged: true,
            previousSearchKeyRef: searchKeyRef,
          });
        } catch (err) {
          await setSearchMode('deepseek');
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'write', message: '绑定成功但写入绑定标记失败' };
          return;
        }
        try {
          await ctx.credentials.set('OPENAI_CODEX_API_KEY', exchanged.access_token);
          codexInjectedToken = exchanged.access_token;
          codexCredentialOwned = true;
        } catch (err) {
          try { clearBindFlag(CODEX_BIND_FILE); } catch (clearErr) { /* 状态仍保持失败，下一次同步会继续清理 */ }
          await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
          oauthLastError = { kind: 'credentials', message: '绑定失败：凭据注入失败' };
          codexBridgeState = { ok: false, lastSyncAt: Date.now(), expiresAt: null, error: oauthLastError, routeConfigured: route.ok };
          return;
        }
        const expiresAtSec = codexExpiresAt(decodeJwtExp(exchanged.access_token), Date.parse(nowIso));
        codexBridgeState = { ok: true, lastSyncAt: Date.now(), expiresAt: expiresAtSec != null ? expiresAtSec * 1000 : null, error: null, routeConfigured: route.ok };
      } catch (err) {
        await rollbackBindingSetup(route, defaultModel, previousAuth, newAccessToken);
        oauthLastError = { kind: 'exception', message: '绑定异常，请重试' };
      } finally {
        if (timer) clearTimeout(timer);
        try { serverHandle.close(); } catch (err) { /* 忽略 */ }
        oauthInFlight = false;
      }
    }

    async function startCodexOAuthRpc() {
      if (oauthInFlight) return { ok: false, oauthInFlight: true, error: { kind: 'in-flight', message: '授权进行中，请稍候' } };
      oauthInFlight = true;
      oauthLastError = null;
      const pkce = createPkcePair();
      const state = randomBytes(16).toString('hex');
      const port = oauthCallbackPort();
      const waitCode = deferred();
      const serverHandle = await startOAuthCallbackServer(state, function (code) { waitCode.resolve(code); }, port);
      if (!serverHandle) {
        oauthInFlight = false;
        return { ok: false, oauthInFlight: false, error: { kind: 'port-busy', message: '回调端口 ' + port + ' 被占用，请关闭占用程序（如正在运行的 codex 登录）后重试' } };
      }
      const authorizeUrl = buildAuthorizeUrl(state, pkce.challenge);
      runCodexOAuthFlow(pkce, state, serverHandle, authorizeUrl, waitCode).catch(function () {
        oauthLastError = { kind: 'exception', message: '绑定异常，请重试' };
      });
      return { ok: true, authorizeUrl: authorizeUrl, oauthInFlight: true };
    }

    async function unbindCodexRpc() {
      if (oauthInFlight) return { ok: false, error: { kind: 'in-flight', message: '授权进行中，请先完成或等待超时' } };
      try {
        const flag = readBindFlag(CODEX_BIND_FILE);
        await removeOwnedCodexRoute(flag);
        codexRouteOwned = false;
        await restoreDefaultModel(flag);
        const cleared = await clearInjectedCodexCredential(flag);
        if (!cleared) throw new Error('credentials cleanup failed');
        const searchRoute = await setSearchMode('deepseek');
        if (!searchRoute.ok) throw new Error('search route restore failed');
        clearBindFlag(CODEX_BIND_FILE);
        codexBridgeState = { ok: false, lastSyncAt: Date.now(), expiresAt: null, error: { kind: 'unbound', message: '已解绑 ChatGPT 订阅，请重新授权绑定' }, routeConfigured: false };
        return { ok: true, bound: false };
      } catch (err) {
        return { ok: false, error: { kind: 'exception', message: '解绑失败，请重试' } };
      }
    }

    function getCodexBridgeStatusRpc() {
      const flag = readBindFlag(CODEX_BIND_FILE);
      return {
        ok: codexBridgeState.ok,
        bound: flag.bound,          // 绑定标记是唯一事实
        oauthInFlight: oauthInFlight,
        expiresAt: codexBridgeState.expiresAt,
        lastSyncAt: codexBridgeState.lastSyncAt,
        error: oauthLastError || codexBridgeState.error,
        routeConfigured: codexBridgeState.routeConfigured,
      };
    }

    // ---------- RPC 路由（webServer HTTP，JSON 进出，同源防护） ----------
    const ROUTE_PREFIX = '/_dsh/dsh-chatgpt-subscription';
    const ROUTES = {
      getCodexBridgeStatus: function () { return getCodexBridgeStatusRpc(); },
      startCodexOAuth: function () { return startCodexOAuthRpc(); },
      unbindCodex: function () { return unbindCodexRpc(); },
    };
    const MUTATING = { startCodexOAuth: true, unbindCodex: true }; // 所有有副作用的方法需同源，防跨站触发授权或清理

    function sameOrigin(req) {
      const fetchSite = (req.headers && (req.headers['sec-fetch-site'] || '')) || '';
      const origin = (req.headers && req.headers.origin) || '';
      const host = (req.headers && req.headers.host) || '';
      if (origin) return host.length > 0 && (origin === 'http://' + host || origin === 'https://' + host);
      return fetchSite === 'same-origin' || fetchSite === 'none';
    }

    function readBody(req, maxBytes) {
      return new Promise(function (resolve, reject) {
        let size = 0;
        const chunks = [];
        req.on('data', function (c) { size += c.length; if (size > maxBytes) { reject(Object.assign(new Error('payload too large'), { status: 413 })); req.destroy(); return; } chunks.push(c); });
        req.on('end', function () { resolve(Buffer.concat(chunks).toString('utf8')); });
        req.on('error', reject);
      });
    }

    function respond(res, status, payload) {
      res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' });
      res.end(JSON.stringify(payload));
    }

    ctx.inject(['webServer'], function (webCtx) {
      try {
        const dispose = webCtx.webServer.register({
          kind: 'prefix',
          path: ROUTE_PREFIX,
          handler: async function (req, res) {
            try {
              // handler 只收 (req, res) 两参；pathname 须从 req.url 自行解析（官方 webServer 契约）
              const url = new URL(req.url || '/', 'http://localhost');
              const path = url.pathname;
              if (!path.startsWith(ROUTE_PREFIX + '/')) { respond(res, 404, { error: 'not found' }); return; }
              const method = decodeURIComponent(path.slice(ROUTE_PREFIX.length + 1));
              if (!Object.hasOwn(ROUTES, method)) { respond(res, 404, { error: 'unknown method: ' + method }); return; }
              if (Object.hasOwn(MUTATING, method)) {
                if (req.method !== 'POST') { respond(res, 405, { error: 'mutating methods require POST' }); return; }
                if (!sameOrigin(req)) { respond(res, 403, { error: 'cross-origin request rejected' }); return; }
              }
              let args = null;
              if (req.method === 'POST') {
                const raw = await readBody(req, 64 * 1024);
                if (raw.length > 0) { try { args = JSON.parse(raw); } catch (e) { respond(res, 400, { error: 'invalid JSON body' }); return; } }
              }
              const result = await ROUTES[method](args);
              respond(res, 200, result);
            } catch (err) {
              const status = (err && err.status) || 500;
              respond(res, status, { error: status === 500 ? 'internal error' : String((err && err.message) || err) });
            }
          },
        });
        return function () { dispose(); };
      } catch (err) {
        console.warn('[dsh-chatgpt-subscription] webServer 路由注册失败', String((err && err.message) || err));
      }
    }, 'dsh-chatgpt-subscription: Web routes');

    // ---------- 启动即刷 + 30min 令牌看护 ----------
    // 只有绑定标记存在时，syncCodexToken 才注册 ChatGPT 路由；未绑定状态绝不触碰用户配置。
    syncCodexToken();
    syncRoutingMode();
    ctx.interval(syncCodexToken, CODEX_SYNC_INTERVAL_MS);
    // agentDefaultModel 没有变更事件；短轮询只比较选择值并在模式变化时改搜索配置。
    ctx.interval(syncRoutingMode, ROUTING_SYNC_INTERVAL_MS);

    // 停用时恢复原始 DeepSeek 搜索引用；不删除 auth.json 或绑定标记，便于重新启用后继续维护。
    return function () {
      const flag = readBindFlag(CODEX_BIND_FILE);
      if (flag.bound && flag.previousSearchKeyRef) {
        searchKeyRef = flag.previousSearchKeyRef;
        setSearchMode('deepseek').catch(function () {
          // 设置服务可能已先于插件销毁；此边界记录在审计文档，不伪造恢复成功。
        });
      }
    };
  },
};
